import { and, eq } from "drizzle-orm";
import { zodOutputFormat } from "@anthropic-ai/sdk/helpers/zod";
import type { MediaType } from "@resonance/shared";
import { db } from "../../db/index.js";
import {
  libraryItems,
  recommendations,
  type MediaCacheRow,
  type RecommendationRow,
  type LibraryItemRow,
} from "../../db/schema.js";
import { searchAndCacheByTitle } from "../mediaCache.js";
import { getActiveProfile } from "../profile.js";
import { getAnthropic, ONBOARDING_MODEL } from "./client.js";
import { evaluateSystemPrompt } from "./prompts/evaluate.js";
import { aiTimeoutSignal, withAiTimeout } from "./aiTimeout.js";
import { VerdictOutputSchema, type VerdictOutput } from "./schemas.js";
import { getUserLibrary } from "./recommender.js";
import { canonicalizeTitle, collectAvoidTitles } from "./titleMatching.js";
import { formatLibraryBlock } from "./aiHelpers.js";

const EVALUATE_MODEL = ONBOARDING_MODEL;

/**
 * Search the relevant adapter for a title and return the top N hits as
 * already-cached rows. Caller picks one to evaluate.
 *
 * The user explicitly asked for this format, so unlike the recommendation
 * pipeline we don't filter against the user's avoid set here — the user might
 * be re-considering something they previously skipped, and the verdict
 * prompt is designed to address that head-on.
 */
export async function evaluateSearch(
  mediaType: MediaType,
  title: string,
  limit = 3,
): Promise<MediaCacheRow[]> {
  const hits = await searchAndCacheByTitle(mediaType, title);
  return hits.slice(0, limit);
}

export interface EvaluateStatus {
  /** True if the user already has this title in their library_items. */
  inLibrary: boolean;
  /** True if the user has saved/rated this work via a previous recommendation. */
  inSavedRecs: boolean;
  /** True if the user previously skipped or rated 1-2 a recommendation of this title. */
  rejectedBefore: boolean;
  /** True if the title is on profile.dislikedTitles (named negatively in onboarding). */
  inDislikedTitles: boolean;
  /** True if a previous batch already recommended this work (regardless of status). */
  previouslyRecommended: boolean;
}

export interface EvaluateResult {
  candidate: MediaCacheRow;
  verdict: VerdictOutput;
  status: EvaluateStatus;
}

/**
 * Score a single chosen candidate against the user's taste profile and
 * surface status flags so the UI can warn / acknowledge prior interactions.
 *
 * Status flags are computed deterministically from the DB; the verdict text
 * is generated by the model and is also instructed to acknowledge any prior
 * negative interaction it sees in the profile (dislikedTitles).
 */
export async function evaluateCandidate(
  userId: string,
  cacheRow: MediaCacheRow,
): Promise<EvaluateResult> {
  const profileRow = await getActiveProfile(userId);
  if (!profileRow) {
    const err: Error & { status?: number } = new Error(
      "Cannot evaluate: user has no taste profile yet",
    );
    err.status = 400;
    throw err;
  }
  const profile = profileRow.profileData;

  const [library, avoidTitles] = await Promise.all([
    getUserLibrary(userId, profile),
    collectAvoidTitles(userId, profile),
  ]);

  const [existingRec, existingLibraryRow] = await Promise.all([
    db.query.recommendations.findFirst({
      where: and(
        eq(recommendations.userId, userId),
        eq(recommendations.mediaCacheId, cacheRow.id),
      ),
    }),
    db.query.libraryItems.findFirst({
      where: and(
        eq(libraryItems.userId, userId),
        eq(libraryItems.mediaType, cacheRow.mediaType),
        eq(libraryItems.title, cacheRow.normalizedData.title),
      ),
    }),
  ]);

  const status = computeStatus({
    cacheRow,
    existingRec: existingRec ?? null,
    existingLibraryRow: existingLibraryRow ?? null,
    avoidTitles,
    dislikedTitles: profile.dislikedTitles ?? [],
  });

  const client = getAnthropic();

  const sections: string[] = [
    `# User profile\n\n${JSON.stringify(profile, null, 2)}`,
  ];

  if (library.length > 0) {
    sections.push(
      `# User's library (works they personally loved — REFERENCE these by name in the verdict whenever a theme overlaps)\n\n${formatLibraryBlock(library)}`,
    );
  }

  const item = cacheRow.normalizedData;
  sections.push(
    `# Candidate\n\nTitle: ${item.title}\nFormat: ${item.mediaType}\nYear: ${item.year ?? "?"}\nRating: ${item.rating ?? "?"}\nGenres: ${item.genres.slice(0, 6).join(", ") || "—"}\nSynopsis: ${truncate(item.description, 800)}`,
  );

  sections.push(`# Task\n\nGive your honest verdict.`);

  const response = await withAiTimeout(() =>
    client.messages.parse({
      model: EVALUATE_MODEL,
      max_tokens: 800,
      system: evaluateSystemPrompt(),
      messages: [{ role: "user", content: sections.join("\n\n") }],
      output_config: {
        format: zodOutputFormat(
          VerdictOutputSchema as unknown as Parameters<
            typeof zodOutputFormat
          >[0],
        ),
      },
    }, { signal: aiTimeoutSignal() }),
  );

  if (!response.parsed_output) {
    throw new Error(`Evaluate failed (stop_reason=${response.stop_reason})`);
  }

  const verdict = VerdictOutputSchema.parse(response.parsed_output);
  return { candidate: cacheRow, verdict, status };
}

function computeStatus(args: {
  cacheRow: MediaCacheRow;
  existingRec: RecommendationRow | null;
  existingLibraryRow: LibraryItemRow | null;
  avoidTitles: Set<string>;
  dislikedTitles: string[];
}): EvaluateStatus {
  const {
    cacheRow,
    existingRec,
    existingLibraryRow,
    avoidTitles,
    dislikedTitles,
  } = args;

  const titleCanonical = canonicalizeTitle(cacheRow.normalizedData.title);
  const inDislikedTitles = dislikedTitles.some(
    (t) => canonicalizeTitle(t) === titleCanonical,
  );
  const matchedAvoid = avoidTitles.has(titleCanonical);

  const status: EvaluateStatus = {
    inLibrary: existingLibraryRow != null,
    inSavedRecs:
      existingRec?.status === "saved" ||
      (existingRec?.status === "rated" && (existingRec.rating ?? 0) >= 4),
    rejectedBefore:
      existingRec?.status === "skipped" ||
      (existingRec?.status === "rated" && (existingRec.rating ?? 5) <= 2) ||
      // matchedAvoid catches the library-import-rated-low case (where there's
      // no rec row but an avoid-set entry).
      (matchedAvoid && existingRec == null),
    inDislikedTitles,
    previouslyRecommended: existingRec != null,
  };
  return status;
}

function truncate(s: string, max: number): string {
  if (s.length <= max) return s;
  return s.slice(0, max - 1).trimEnd() + "…";
}
