import { Router } from "express";
import { z } from "zod";
import { eq } from "drizzle-orm";
import { requireUser } from "../middleware/auth.js";
import { db } from "../db/index.js";
import { mediaCache } from "../db/schema.js";
import {
  evaluateCandidate,
  evaluateSearch,
} from "../services/ai/evaluate.js";
import { checkRateLimit } from "../services/rateLimit.js";

export const evaluateRouter: Router = Router();

evaluateRouter.use(requireUser);

const mediaTypeEnum = z.enum([
  "movie",
  "tv",
  "anime",
  "manga",
  "game",
  "book",
]);

const searchBodySchema = z
  .object({
    title: z.string().trim().min(1).max(200),
    mediaType: mediaTypeEnum,
  })
  .strict();

/**
 * POST /api/evaluate/search
 * Body: { title, mediaType }
 * Returns up to 3 cached candidates so the user can disambiguate before
 * spending an AI call on a verdict.
 */
evaluateRouter.post("/search", async (req, res, next) => {
  try {
    const parsed = searchBodySchema.safeParse(req.body ?? {});
    if (!parsed.success) {
      res
        .status(400)
        .json({ error: "invalid body", issues: parsed.error.issues });
      return;
    }
    const rows = await evaluateSearch(
      parsed.data.mediaType,
      parsed.data.title,
      3,
    );
    // Return the normalized media items so the client can render the picker
    // without an extra round-trip; include the cache id so /score can pin to it.
    res.json({
      matches: rows.map((r) => ({
        mediaCacheId: r.id,
        item: r.normalizedData,
      })),
    });
  } catch (err) {
    next(err);
  }
});

const scoreBodySchema = z
  .object({ mediaCacheId: z.string().uuid() })
  .strict();

/**
 * POST /api/evaluate/score
 * Body: { mediaCacheId }
 * Returns the verdict + status flags. Status flags are computed against the
 * user's profile/library; verdict is generated by the model.
 */
evaluateRouter.post("/score", async (req, res, next) => {
  try {
    const parsed = scoreBodySchema.safeParse(req.body ?? {});
    if (!parsed.success) {
      res
        .status(400)
        .json({ error: "invalid body", issues: parsed.error.issues });
      return;
    }

    try {
      checkRateLimit(req.user!.id, "evaluate.score");
    } catch (err) {
      const status =
        err instanceof Error && "status" in err
          ? Number((err as { status?: number }).status) || 429
          : 429;
      res
        .status(status)
        .json({ error: err instanceof Error ? err.message : "rate limited" });
      return;
    }

    const cacheRow = await db.query.mediaCache.findFirst({
      where: eq(mediaCache.id, parsed.data.mediaCacheId),
    });
    if (!cacheRow) {
      res.status(404).json({ error: "media not found" });
      return;
    }

    const result = await evaluateCandidate(req.user!.id, cacheRow);
    res.json({
      candidate: {
        mediaCacheId: result.candidate.id,
        item: result.candidate.normalizedData,
      },
      verdict: result.verdict,
      status: result.status,
    });
  } catch (err) {
    next(err);
  }
});
